name: Cypress cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs: 
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps: 
    - name: Get code
      uses: actions/checkout@v4.2.2

    - name: Cypress run
      uses: cypress-io/github-action@v6.5.0
      with:
        install-command: yarn install
        browser: electron
        record: true
        group: UI Electron
        spec: ${{ github.events.inputs.spec }}
      env:
        CYPRESS_RECORD_KEY: 786890a0-2632-41aa-a667-91fe68f04d02
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
